---
- name: Verify vagrant installation
  command: "which vagrant"
  register: vagrant_present
  changed_when: vagrant_present.rc == 0
  failed_when: vagrant_present.rc != 0
  tags: [ 'vagrant', 'verify' ]

- name: Install boxes
  command: "vagrant box add {{ item.name }} {{ item.box_url }}"
  register: vagrant_box_install
  changed_when: vagrant_box_install.rc == 0
  failed_when: vagrant_box_install.rc != 0
  with_items:
    - "{{ vagrant_boxes }}"
  loop_control:
    label: "Installing vagrant box {{ item.name }}"
  tags: [ 'vagrant', 'box', 'install' ]
